---
title: "Primary Care Provider Leaflet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Leaflet Map

```{r load-libraries}

# load libraries
library(leaflet)
library(tidyverse)
library(htmlwidgets)
library(fontawesome)
#library(icons)
```


```{r data import, echo = FALSE}

# read csv files
pcp_scrape_df <- read_csv("data/primary care providers/maine_primary_care_scrape.csv")
federal_health_centers <- read_csv("data/primary care providers/federally_recognized_health_centers.csv")

# reformatting
federal_health_centers <- federal_health_centers %>%
  mutate(`Facility Type` = str_replace(`Health Center Service Delivery Site Location Setting Description`, 
          "All Other Clinic Types", 
          "Clinic"))

```


```{r scraped_primary-care-provider-leaflet}

maine_icons_scrape <- awesomeIconList(
  `Doctor` = makeAwesomeIcon(
  icon = "user-md",
  library = "fa",
  markerColor = "lightred"
),
  `Family practice physician` = makeAwesomeIcon(
  icon = "users",
  library = "fa",
  markerColor = "green"
),
  `Medical clinic` = makeAwesomeIcon(
  icon = "plus-square",
  library = "fa",
  markerColor = "beige"
),
  `Medical office` = makeAwesomeIcon(
  icon = "plus-square",
  library = "fa",
  markerColor = "blue"
),
  `Medical group` = makeAwesomeIcon(
  icon = "plus-square",
  library = "fa",
  markerColor = "purple"
),
  `Internist`  = makeAwesomeIcon(
  icon = "user-md",
  library = "fa",
  markerColor = "orange"
),
  `Medical Center` = makeAwesomeIcon(
  icon = "plus-square",
  library = "fa",
  markerColor = "lightred"
),
  `Reproductive health clinic` = makeAwesomeIcon(
  icon = "heart",
  library = "fa",
  markerColor = "pink"
),
  `Home health care service` = makeAwesomeIcon(
  icon = "home",
  library = "fa",
  markerColor = "yellow"
),
  `General practitioner` = makeAwesomeIcon(
  icon = "user-md",
  library = "fa",
  markerColor = "beige"
),
  `Hospital` = makeAwesomeIcon(
  icon = "h-square",
  library = "fa",
  markerColor = "orange"
),
  `Emergency care physician` = makeAwesomeIcon(
  icon = "medkit",
  library = "fa",
  markerColor = "purple"
),
  `Podiatrist` = makeAwesomeIcon(
  icon =  "user-md",
  library = "fa",
  markerColor = "teal"
),
  `Children's hospital` = makeAwesomeIcon(
  icon =  "h-square",
  library = "fa",
  markerColor = "white"
)
)

# make popup text with name, address, notes, and link to website
pcp_scrape_df <-
  pcp_scrape_df %>% 
  mutate(full_website = paste("<b><a href='https://www.", website,"' target='_blank'>", title,"</a></b>", "<br/>", sep = "")) 

# make popup text with name, address, notes, and link to website
pcp_scrape_labels <- sprintf(
  "<strong>%s</strong><br/>%s<br/><strong>Rating: %g of 5</strong>",
  pcp_scrape_df$full_website, pcp_scrape_df$address, pcp_scrape_df$rating
) %>% lapply(htmltools::HTML)


# setup basemap
pcp_scrape_leaflet <- 
  leaflet() %>% 
  addTiles() %>%
  addMarkers(~pcp_scrape_df$longitude, 
             ~pcp_scrape_df$latitude, 
             data = pcp_scrape_df, 
             group = pcp_scrape_df$category, 
             popup = ~pcp_scrape_labels)
  

pcp_scrape_leaflet <- 
      leaflet(data = pcp_scrape_df) %>%
      addTiles() %>% addAwesomeMarkers(
      ~longitude,
      ~latitude,
      popup = ~pcp_scrape_labels,
      icon = ~maine_icons_scrape[category], 
      group = ~category)

# add layer controls to map 
pcp_scrape_leaflet <- 
  pcp_scrape_leaflet %>% 
  addLayersControl(
    overlayGroups = pcp_scrape_df$category,
    options = layersControlOptions(collapsed = FALSE)
  )

# save widget 
saveWidget(pcp_scrape_leaflet, "maine_pcp.html")

```

```{r federal-health-centers-leaflet}

maine_icons_fed <- awesomeIconList(
  `Clinic` = makeAwesomeIcon(
  icon = "plus-square",
  library = "fa",
  markerColor = "lightred"
),
  `School` = makeAwesomeIcon(
  icon = "graduation-cap",
  library = "fa",
  markerColor = "green"
),
  `Nursing Home` = makeAwesomeIcon(
  icon = "wheelchair",
  library = "fa",
  markerColor = "beige"
),
  `Unknown` = makeAwesomeIcon(
  icon = "question-circle",
  library = "fa",
  markerColor = "blue"
)
)

# make popup text with name, address, notes, and link to website
fed_labels <- sprintf(
  "<strong>%s</strong><br/>%s, %s ME<br/>%s",
  federal_health_centers$`Site Name`, 
  federal_health_centers$`Site Address`, 
  federal_health_centers$`Site City`,
  federal_health_centers$`Site Telephone Number`
) %>% lapply(htmltools::HTML)


# setup basemap
fed_leaflet <- 
  leaflet() %>% 
  addTiles() %>%
  addMarkers(~federal_health_centers$`Geocoding Artifact Address Primary X Coordinate`, 
             ~federal_health_centers$`Geocoding Artifact Address Primary Y Coordinate`, 
             data = federal_health_centers, 
             group = federal_health_centers$`Facility Type`, 
             popup = ~fed_labels)
  

fed_leaflet <- 
      leaflet(data = federal_health_centers) %>%
      addTiles() %>% addAwesomeMarkers(
      ~`Geocoding Artifact Address Primary X Coordinate`,
      ~`Geocoding Artifact Address Primary Y Coordinate`,
      popup = ~fed_labels,
      icon = ~maine_icons_fed[`Facility Type`], 
      group = ~`Facility Type`)

# add layer controls to map 
fed_leaflet <- 
  fed_leaflet %>% 
  addLayersControl(
    overlayGroups = federal_health_centers$`Facility Type`,
    options = layersControlOptions(collapsed = FALSE)
  )

# save widget 
saveWidget(fed_leaflet, "maine_pcp_fed.html")

```


