---
title: "Population and Lyme Disease Prevalence of Maine Cities"
output: 
  html_document:
     toc: TRUE
     number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Load Packages

```{r libraries, echo = FALSE}

library(tidyverse) 
library(leaflet) 
library(sf) 
library(RColorBrewer) 
library(htmltools) 
library(leafsync) 
library(kableExtra) 
library(tidycensus)
library(rvest)
library(DT)
library(fedmatch)


```

# Import and Clean Data

```{r data-import, echo = FALSE}

# read shape files
me_cities <- st_read("data/demographics/spatial/cities/tl_2016_23_place.shp")

# read csv files
me_pop <- read_csv("data/demographics/maine_city_population.csv")
tick_towns <- read_csv("/cloud/project/data/ticks/tickborne_prevalence_town.csv")

# join population data with spatial data
me_spatial <- me_cities %>%
  left_join(me_pop, by= "NAME")

```

```{r change-coordinate-reference-system, echo = FALSE}

# set CRS
me_cities <- st_transform(me_cities, "+init=epsg:4326")
me_spatial <- st_transform(me_spatial, "+init=epsg:4326")

# report CRS
st_crs(me_cities)
st_crs(me_spatial)

```

# Cities Leaflet

```{r generate-cities-leaflet-basemap, echo = FALSE}

# set view and add texture
me_cities_bm <- leaflet(data = me_cities) %>% #<<
  addProviderTiles(providers$Stamen.Terrain) %>%
  setView(lng = -69.5, 
          lat = 45.3, 
          zoom = 6.5)

# add city borders
me_cities_bm %>%
  addPolygons(
    opacity = 1,
    color = "blue", 
    weight = 2) 
```

```{r generate-cities-leaflet-labels, echo = FALSE}

# create labels
me_cities_labels <- sprintf("<strong>%s</strong><br/>geoid # %s ", 
                  me_cities$NAME, me_cities$GEOID) %>% lapply(htmltools::HTML)

```


```{r first-cities-leaflet-map, eval=TRUE}
me_cities_map <- me_cities_bm %>%
  addPolygons(
      color = "blue", 
      opacity = 1,
      weight = 2,
    highlight = highlightOptions( #<<
        weight = 3, #<<
        color = "green", #<<
        fillOpacity = 1, #<<
        bringToFront = TRUE)) #<< 

me_cities_map
```

 
# Counties Leaflet

```{r generate-counties-leaflet-basemap, echo = FALSE}

# set view and add texture
# me_counties_bm <- leaflet(data = me_counties) %>% #<<
#  addProviderTiles(providers$Stamen.Terrain) %>%
#  setView(lng = -69.5, 
#          lat = 45.3, 
#          zoom = 6.5)

# add city borders
# me_counties_bm %>%
#  addPolygons(
#    opacity = 1,
#    color = "blue", 
#    weight = 2) 
```

```{r generate-counties-leaflet-labels, echo = FALSE}

# create labels
# me_counties_labels <- sprintf("<strong>%s</strong><br/>objectid # %s ", 
#                  me_counties$NAME, me_counties$OBJECTID) %>% lapply(htmltools::HTML)

```


```{r first-counties-leaflet-map, eval=TRUE}

# me_counties_map <- me_counties_bm %>%
#  addPolygons(
#      color = "blue", 
#      opacity = 1,
#      weight = 2,
#    highlight = highlightOptions( #<<
#        weight = 3, #<<
#        color = "green", #<<
#        fillOpacity = 1, #<<
#        bringToFront = TRUE)) #<< 

# me_counties_map
```

## Gathering Census Data

```{r census-data-api}

# apply api key
census_api_key("5177724b01a7fe4714097e711cb95230c37cfce7", install = TRUE, overwrite = TRUE)

```


```{r }

# import census data
census_df <- get_acs(geography = "place", variables = c("B01003_001E"), state = "ME", geometry = TRUE)
census_df2 <- get_acs(geography = "county subdivision", variables = c("B01003_001E"), state = "ME", geometry = TRUE)

# reformat location variables
census_df <- census_df %>%
  separate(NAME, into = c("Place", "State"), sep = ",") %>%
  mutate(Place = str_remove(Place, " CDP| city"))

# reformat location variables
census_df2 <- census_df2 %>%
  separate(NAME, into = c("Place", "County", "State"), sep = ",") %>%
  mutate(Place = str_remove(Place, "town"))

# visualize polygons using ggplot
ggplot(census_df) +
    geom_sf(aes(fill = estimate))

# visualize polygons using ggplot
ggplot(census_df2) +
    geom_sf(aes(fill = estimate))

```

```{r tick-and-population-leafelt}

# set CRS
census_df <- st_transform(census_df, "+init=epsg:4326")
census_df2 <- st_transform(census_df, "+init=epsg:4326")

# join tick data with census data
tick_census_df <- tick_towns %>%
  left_join(census_df, by = c("town" = "Place"))

# create labels
pop_labels <- sprintf(
  "<strong>%s (2019)</strong> <br/>Population: %g",
   census_df$Place, census_df$estimate
) %>% lapply(htmltools::HTML)

tick_labels <- sprintf(
  "<strong>%s (2019)</strong> <br/>Positive Lyme Tests: %g, <br/> Positivity Rate: %s",
  tick_towns$town, tick_towns$borrelia_positive, tick_towns$borrelia_percent
) %>% lapply(htmltools::HTML)

# create layer names
Groupnames <- c("Population", "Positive Lyme Tests")

# define bins
bins1 <- seq(0, 80000, by = 10000)
bins2 <- seq(0, 30, by = 3)

# select color palettes
pal1 <- colorBin("OrRd", domain = census_df$estimate, bins = bins)
pal2 <- colorBin("PuRd", domain = tick_towns$borrelia_positive, bins = bins2)

# generate leaflet
leaflet(census_df) %>%
  addProviderTiles(providers$Stamen.Terrain) %>%
  addProviderTiles(providers$Stamen.TerrainLabels) %>%
  addPolygons(fillColor = ~pal1(census_df$estimate),
              color = "black",
              weight = 1,
              fillOpacity = 0.9,
              label = ~pop_labels,
              group = "Population") %>%
  addPolygons(fillColor = ~pal2(tick_towns$borrelia_positive),
              color = "black",
              weight = 1,
              fillOpacity = 0.9,
              label = ~tick_labels,
              group = "Positive Lyme Tests") %>%
  setView(lng = -69.5, 
          lat = 45.3, 
          zoom = 6.5) %>%
   addLayersControl(
     baseGroups = Groupnames,
     options = layersControlOptions(collapsed = FALSE)
  ) 

```


```{r tick-towns-missing-from-census-data, echo = FALSE}

missing_ticktown <- anti_join(tick_towns, census_df, by = c("town" = "Place")) %>%
                    select(town, borrelia_positive, borrelia_tests)

DT::datatable(missing_ticktown,
              options = list(
                paging = TRUE,
                pageLength = 10),
              height = 500)
              
```


```{r census-towns-missing-from-tick-data, echo = FALSE}

missing_censustown <- anti_join(census_df, tick_towns, by = c("Place" = "town")) %>%
                      select(Place, estimate, moe)

DT::datatable(missing_censustown,
              options = list(
                paging = TRUE,
                pageLength = 10),
              height = 500)
              
```

```{r fuzzy-match, echo = FALSE}

tick_towns$row_num <- seq.int(nrow(tick_towns)) 

fuzzy_result <- merge_plus(data1 = census_df, data2 = tick_towns,
                           by.x = "Place", by.y = "town",
                           match_type = "fuzzy",
                           fuzzy_settings = build_fuzzy_settings(
                             p = 0.1,
                             maxDist = 0.15),
                           unique_key_1 = "GEOID", unique_key_2 = "row_num")

DT::datatable(fuzzy_result[[1]],
              options = list(
                paging = TRUE,
                pageLength = 10),
              height = 500)
              
```
