---
title: "Maine Ticks Project Info Sheet"
author: "Laurie Baker and Matt Clayton"
date: "5/1/2022"
output: 
   prettydoc::html_pretty:
     theme: cayman
     toc: TRUE
     toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Community Partner Background

**Dr. Susan Elias**

Susan is a staff scientist at the Maine Medical Center Research Institute's Vector-Borne Disease Laboratory with a focus in the following research areas:

1.  Ecology of tick and mosquito vectors and vector-borne disease agents as related to climate, hosts, habitat, and human behavior
2.  Modeling environmental spatio-temporal disease risk
3.  Disease risk communication

**Dr. Robert Smith**

Rob is both the the Director of the Vector-Borne Disease Laboratory and the director of the Division of Infectious Disease at Maine Medical Center with the following research interests:

1.  Molecular epidemiology and ecology of emergent vector-borne diseases
2.  Clinical recognition and diagnosis of emergent vector-borne diseases

**Vector-Borne Disease Laboratory**

The goal of this lab is to investigate the spread of disease-carrying ticks and mosquitoes in Maine and the disease agents they carry. The researchers in the lab also develop new strategies for tick control, and based on this work, inform the public about their risk and how to prevent it. (overview reported from <https://mmcri.org/>)

## Project Overview

Maine has very high rates of tickborne diseases, relative to other states in the US. There are also many areas of Maine that are historically under-served when it comes to medical coverage. Using data from case reports, surveys, and tick submissions, we can better understand the spread of tickborne diseases in Maine and we can begin to visualize areas of Maine that are at an increased risk. In addition, using data on health care providers in Maine we can identify areas of Maine that appear to be under-served. Combining all of this data could ultimately be very beneficial for both Maine citizens and also for the public health sector.

## Main data science questions (Includes any key questions you hope the challenge will answer)

-   Why do most Lyme disease cases appear to occur in mid-coast Maine? Could the data be skewed by reporting biases? What are some of the main factors at play (population, outdoor recreation, age of population, etc...)?

-   Are there specific areas of Maine that suffer from a lack of health care coverage? Do these under-served areas have an increased risk for getting sick with Lyme disease?

## How will addressing this challenge benefit the community you serve?

First of all, understanding historical tickborne disease data can help policy makers gain a better sense of how common tickborne diseases are in humans, and possibly what to expect in the future regarding tickborne diseases in Maine. How large is the risk associated with contracting tickborne diseases, and what areas of Maine seem to be the most vulnerable? This could also possibly inform policy makers to take preventative action against the spread of tickborne diseases.

Secondly, addressing this challenge could help inform Maine citizens or Maine vacationers about the levels of risk in different parts of the state. For instance, maybe people don't have much to worry about in or around Portland where there seems to be plenty of health care coverage, but it more rural parts of the state, should people be more cautious?

## Data sets

| Usage                                     | Description                                                                                                                                    |
|:--------------------------|:--------------------------------------------|
| `federally_recognized_health_centers.csv` | List of all the federally-funded health centers in Maine that provide health services (Health Resources and Services Administration - HRSA)    |
| `maine_primary_care_scrape.csv`           | List of primary care providers and other related medical practices in the state of Maine, scraped from google maps.                            |
| `umaine_tickborne_prevalence_town.csv`    | 4-year prevalence data (2019-2022) for 6 different pathogens found in ticks (UMaine)                                                           |
| `maine_tracking_network_incidence.csv`    | 5-year totals (2016-2020) of Lyme disease, Anaplasmosis, and Babesiosis cases by town (Maine CDC)                                              |
| `maine_tracking_network_rate.csv`         | 5-year incidence rates (positive cases per 100,000 people, 2016-2020) for Lyme disease, Anaplasmosis, and Babesiosis cases by town (Maine CDC) |

## Key Milestones and Project/Outcome partners hope to achieve?

-   Determine areas of Maine where citizens and/or vacationers are at the highest risk of contracting and getting seriously sick with tickborne diseases.

-   Determine where cases of tickborne diseases in humans are most common, and whether it is likely that these areas will continue to have high rates of tickborne diseases.

-   Identify some of the most important factors that impact case rates in Maine, and identify potential sources of biasesness in tickborne disease data.

## Resources and Background Reading

[Maine Tracking Network Tickborne Disease Data Portal](https://gateway.maine.gov/cognos/cgi-bin/cognosisapi.dll?b_action=cognosViewer&ui.action=run&ui.object=%2fcontent%2ffolder%5B%40name%3d%27CDC%20EOHP%20EPHT%20AVR%27%5D%2freportView%5B%40name%3d%27Maine%20Environmental%20Public%20Health%20Tracking%20%28EPHT%29%20Network%20-%20Public%20Data%20Portal%27%5D&cv.header=false&cv.toolbar=false)

[Data For Primary Care Shortage Areas in Maine](https://data.hrsa.gov/data/download?data=HSCD#HSCD) (see "Shortage Areas" tab)

[Overview of Tickborne Diseases in Maine](https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/vector-borne/lyme/tick-attachment-and-tickborne-diseases.shtml?msclkid=06e0a64bc9c211ec98deeac1f5ec6ba1) (Maine CDC)
